export const ADD_TODO = 'ADD_TODO';
export const FETCH_FROM_API = 'FETCH_FROM_API';
export const UPDATE_COLLECTIONID_OPTS = 'UPDATE_COLLECTIONID_OPTS'
export const UPDATE_SLUG_OPTS = 'UPDATE_SLUG_OPTS'
export const UPDATE_GITLABAPIURL_OPTS = 'UPDATE_GITLABURL'
export const UPDATE_PRIVATETOKEN_OPTS = 'UPDATE_PRIVATETOKEN'
export const FETCH_FROM_SNAPSHOT = 'FETCH_FROM_SNAPSHOT'
